name: hamster_pos_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For State Management
  flutter_riverpod: ^2.5.1
  
  # For Networking
  dio: ^5.5.0+1
  
  # For Local Storage (saving the JWT token)
  shared_preferences: ^2.2.3
  
  # For Routing/Navigation
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true